# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Discocli < Formula
  desc "Discord CLI — sync, search, send from your terminal. MCP-ready for AI agents."
  homepage "https://github.com/virat-mankali/discord-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/virat-mankali/discord-cli/releases/download/v0.1.0/discocli_darwin_amd64.tar.gz"
      sha256 "3bc5069acb22e189bdb1280a4d64e0d245a72fff693fb99941990c8d7e1274c9"

      define_method(:install) do
        bin.install "discocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/virat-mankali/discord-cli/releases/download/v0.1.0/discocli_darwin_arm64.tar.gz"
      sha256 "ec9393257aabe52d18175deda43edf7838dac339c8cf8141c1760603f34200d5"

      define_method(:install) do
        bin.install "discocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/virat-mankali/discord-cli/releases/download/v0.1.0/discocli_linux_amd64.tar.gz"
      sha256 "c87ad782751fda2807db755ce0b6f3b6c6f1ec0dcbc0a71286dd639135566d46"
      define_method(:install) do
        bin.install "discocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/virat-mankali/discord-cli/releases/download/v0.1.0/discocli_linux_arm64.tar.gz"
      sha256 "091897e8b14aaa85f762e652a661b416fd346526b1d2890fbbb5ea19a265261a"
      define_method(:install) do
        bin.install "discocli"
      end
    end
  end

  test do
    system "#{bin}/discocli", "--version"
  end
end
