# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Discocli < Formula
  desc "Discord CLI — sync, search, send from your terminal. MCP-ready for AI agents."
  homepage "https://github.com/virat-mankali/discord-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/virat-mankali/discord-cli/releases/download/v0.1.0/discocli_darwin_amd64.tar.gz"
      sha256 "7aaa179e203ec7c099be69fbb7e0a4ca764924dd34dec69f86dab92dc1c2db8e"

      define_method(:install) do
        bin.install "discocli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/virat-mankali/discord-cli/releases/download/v0.1.0/discocli_darwin_arm64.tar.gz"
      sha256 "a1b3a1ffaa6b1a3551683aa4fe87cee7fe3447c9b6301256707721e98fe9e907"

      define_method(:install) do
        bin.install "discocli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/virat-mankali/discord-cli/releases/download/v0.1.0/discocli_linux_amd64.tar.gz"
      sha256 "f221d9365e8389ca3188beb781fd24724cbdd85dc727d298ad6e9159fdddabdd"
      define_method(:install) do
        bin.install "discocli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/virat-mankali/discord-cli/releases/download/v0.1.0/discocli_linux_arm64.tar.gz"
      sha256 "8f6c899f5d3410f424934e119e8c476fbb253e5ec5a682a6c6de20981990b790"
      define_method(:install) do
        bin.install "discocli"
      end
    end
  end

  test do
    system "#{bin}/discocli", "--help"
  end
end
