# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedditMcp < Formula
  desc "Reddit CLI + MCP tool for browsing, posting, search, and automation"
  homepage "https://github.com/virat-mankali/reddit-mcp"
  version "1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/virat-mankali/reddit-mcp/releases/download/v1.0/reddit-mcp_1.0_darwin_amd64.tar.gz"
      sha256 "7196cd68b4365e837796954af5d36894ebb673f4ba70a79bf77e72b5d5262b96"

      define_method(:install) do
        bin.install "rdcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/virat-mankali/reddit-mcp/releases/download/v1.0/reddit-mcp_1.0_darwin_arm64.tar.gz"
      sha256 "1f64a917c6c477f3ff6060d2dcb972e4bf3383aa9ac81fc267554725f8eba968"

      define_method(:install) do
        bin.install "rdcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/virat-mankali/reddit-mcp/releases/download/v1.0/reddit-mcp_1.0_linux_amd64.tar.gz"
      sha256 "2b37f817865b5de2ce0fe4f1a007eb3b49a79b4204d1c739b11cd11552998610"
      define_method(:install) do
        bin.install "rdcli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/virat-mankali/reddit-mcp/releases/download/v1.0/reddit-mcp_1.0_linux_armv6.tar.gz"
      sha256 "cc8c04d84ce8823facc206f736eabf430fb58a5dce7d40b748adb3a8f9b19db7"
      define_method(:install) do
        bin.install "rdcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/virat-mankali/reddit-mcp/releases/download/v1.0/reddit-mcp_1.0_linux_arm64.tar.gz"
      sha256 "364c1430366324f4e60f0236d27ea2fa81835754a115d5aa2d6a9b3b9c841492"
      define_method(:install) do
        bin.install "rdcli"
      end
    end
  end

  test do
    system "#{bin}/rdcli --version"
  end
end
